import { MigrationInterface, QueryRunner } from 'typeorm';

export class insertInOme1675388649812 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO public."ome"(nomeOme, diretoriaid)
      VALUES 
        ('DPO', 1),
        ('DIM', 2),
        ('1º BPM', 2),
        ('6º BPM', 2),
        ('11º BPM', 2),
        ('12º BPM', 2),
        ('13º BPM', 2),
        ('16º BPM', 2),
        ('17º BPM', 2),
        ('18º BPM', 2),
        ('19º BPM', 2),
        ('20º BPM', 2),
        ('25º BPM', 2),
        ('26º BPM', 2),
        ('29º BPM', 2),
        ('DIRESP', 3),
        ('1º BIESP', 3),
        ('2º BIESP', 3),
        ('3º BIESP', 3),
        ('4º BIESP', 3),
        ('BPCHOQUE', 3),
        ('BEPI', 3),
        ('BOPE', 3),
        ('BPGD', 3),
        ('BPRP', 3),
        ('BPRV', 3),
        ('BPTRAN', 3),
        ('BPTUR', 3),
        ('CIPCAES', 3),
        ('CIPMOTO', 3),
        ('BPA', 3),
        ('RPMON', 3),
        ('DINTER 1', 4),
        ('2º BPM', 4),
        ('4º BPM', 4),
        ('9º BPM', 4),
        ('10º BPM', 4),
        ('15º BPM', 4),
        ('21º BPM', 4),
        ('22º BPM', 4),
        ('24º BPM', 4),
        ('27º BPM', 4),
        ('28º BPM', 4),
        ('5ª CIPM', 4),
        ('6ª CIPM', 4),
        ('8ª CIPM', 4),
        ('10ª CIPM', 4),
        ('11ª CIPM', 4),
        ('DINTER 2', 5),
        ('3º BPM', 5),
        ('5º BPM', 5),
        ('7º BPM', 5),
        ('8º BPM', 5),
        ('14º BPM', 5),
        ('23º BPM', 5),
        ('1ª CIPM', 5),
        ('2ª CIPM', 5),
        ('4ª CIPM', 5),
        ('7ª CIPM', 5),
        ('9ª CIPM', 5),
        ('2ª EMG', 1),
        ('ADAGRO', 1),
        ('CPA_DPO', 1),
        ('CPO_DPO', 1),
        ('SMV_DPO', 1),
        ('OLS', 1),
        ('SDS', 1),
        ('SEFAZ', 1),
        ('ACG', 1),
        ('AECI', 1),
        ('AG', 1),
        ('APMP', 1),
        ('C.FARM', 1),
        ('C.ODONT', 1),
        ('CAMIL', 1),
        ('CEFD', 1),
        ('CFAP', 1),
        ('CG', 1),
        ('CIMUS', 1),
        ('CMH', 1),
        ('COPOM', 1),
        ('CPM-REC', 1),
        ('CPM-PET', 1),
        ('CPO', 1),
        ('CPP', 1),
        ('CREED', 1),
        ('CRESEP', 1),
        ('CSM/INT', 1),
        ('CSM/MB', 1),
        ('CSM/MOTO', 1),
        ('CTT', 1),
        ('DAL', 1),
        ('DAS', 1),
        ('DASIS', 1),
        ('DEAJA', 1),
        ('DEIP', 1),
        ('DF', 1),
        ('DGA', 1),
        ('DGP', 1),
        ('DIP', 1),
        ('DPJM', 1),
        ('DS', 1),
        ('DTEC', 1),
        ('CH EMG', 1),
        ('OE', 1),
        ('DASDH', 8),
        ('MPPE', 9),
        ('TJPE', 10),
        ('CAMIL', 11);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
    DELETE FROM public."ome"
    WHERE nomeOme IN (
      'DPO', 'DIM', '1º BPM', '6º BPM', '11º BPM', '12º BPM', '13º BPM',
      '16º BPM', '17º BPM', '18º BPM', '19º BPM', '20º BPM', '25º BPM', '26º BPM',
      'DIRESP', '1º BIESP', '2º BIESP', '3º BIESP', 'BPCHOQUE', 'BPGD',
      'BPRP', 'BPRV', 'BPTRAN', 'BPTUR', 'CIPCAES', 'CIPMOTO', 'CIPOMA', 'RPMON',
      'DINTER I', '2º BPM', '4º BPM', '9º BPM', '10º BPM', '15º BPM',
      '21º BPM', '22º BPM', '24º BPM', '27º BPM', '5ª CIPM', '6ª CIPM',
      '8ª CIPM', '10ª CIPM', '11ª CIPM', 'DINTER II', '3º BPM', '5º BPM',
      '7º BPM', '8º BPM', '14º BPM', '23º BPM', '1ª CIPM', '2ª CIPM',
      '4ª CIPM', '7ª CIPM', '9ª CIPM', '2ª EMG', 'ADAGRO', 'AG', 'COPOM',
      'CREED', 'CSMMB', 'CPA_DPO', 'CPO_DPO', 'CSMMOTO', 'DASIS', 'DAS',
      'OLS', 'SDS', 'SEFAZ', 'SMV_DPO'
    );
  `);
  }
}
